### ISSUE TITLE
[ANDROID APP] Impossible recipe from inventory page

### ISSUE THREAD

**Issue by Quentigus** [pepocivs/rotw-front#3]
Hi,

I've an issue with the "WHAT CAN I MAKE?" button on Android.

In my inventory, I have :
- 1 "Hyrule Herb"
- 1 "Spicy Pepper"

And at the "Recipe from Inventory" screen, I have the "Spicy Steamed Fruit" as possible recipe (with 4 "Spicy Pepper")

**Comment by pepocivs** [comment]
Thanks for reporting we are working on it

**Comment by pepocivs** [comment]
Should be fixed with the new version!

Thanks for reporting!
